# SPDX-FileCopyrightText: Copyright Boozt Fashion, AB
# SPDX-License-Identifier: MIT
---
# Checkov configuration
# https://www.checkov.io/2.Basics/CLI%20Command%20Reference.html

framework:
  - terraform

skip-path:
  - examples/
